services:
  ai-chess:
    build: .
    ports:
      - "4343:80"
    volumes:
      - ./AI Chess/Games:/app/Games
    container_name: Ai-chess
    restart: unless-stopped

  database:
    image: postgres:latest
    container_name: Ai-chess-database
    environment:
      POSTGRES_USER: chessuser
      POSTGRES_PASSWORD: chesspassword
      POSTGRES_DB: chessdb
    ports:
      - "5432:5432"
    restart: unless-stopped
