services:
  database:
    image: postgres:latest
    container_name: Ai-chess-database
    environment:
      POSTGRES_USER: chessuser
      POSTGRES_PASSWORD: chesspassword
      POSTGRES_DB: chessdb
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", -f, "http://localhost:5432"]
      interval: 30s
      timeout: 10s
      retries: 5

  # ai-chess:
  #   build: .
  #   environment:
  #     - NeuralConfig__NumberData=50
  #   depends_on:
  #     - database
  #   links:
  #     - database
  #   ports:
  #     - "4343:80"
  #   # volumes:
  #   #   - ./AI Chess/Games:/app/Games
  #   container_name: Ai-chess
  #   restart: unless-stopped
